"""add sales models

Revision ID: 0495e061bf6a
Revises: 27cde667baae
Create Date: 2026-08-17 07:23:28.696583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0495e061bf6a'
down_revision: Union[str, Sequence[str], None] = '27cde667baae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_sales_clients_name')
    )
    op.create_index(op.f('ix_sales_clients_name'), 'sales_clients', ['name'], unique=False)
    op.create_table('sales_products',
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('default_purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('default_sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_products_designation'), 'sales_products', ['designation'], unique=False)
    op.create_table('sales_orders',
    sa.Column('sale_number', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['sales_clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_number', name='uq_sales_orders_number')
    )
    op.create_index(op.f('ix_sales_orders_client_id'), 'sales_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_orders_sale_date'), 'sales_orders', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_orders_sale_number'), 'sales_orders', ['sale_number'], unique=False)
    op.create_table('sales_order_items',
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('purchase_price >= 0', name='ck_sales_item_purchase_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_sales_item_qty_positive'),
    sa.CheckConstraint('sale_price >= 0', name='ck_sales_item_sale_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['sales_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_items_sales_order_id'), 'sales_order_items', ['sales_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_order_items_sales_order_id'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_index(op.f('ix_sales_orders_sale_number'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_sale_date'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_client_id'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_sales_products_designation'), table_name='sales_products')
    op.drop_table('sales_products')
    op.drop_index(op.f('ix_sales_clients_name'), table_name='sales_clients')
    op.drop_table('sales_clients')
    # ### end Alembic commands ###
