"""add delivery note

Revision ID: 0ee2e484bc63
Revises: 79b7446716bb
Create Date: 2026-09-07 21:46:52.006453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee2e484bc63'
down_revision: Union[str, Sequence[str], None] = '79b7446716bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_delivery_notes',
    sa.Column('delivery_number', sa.String(length=30), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['sales_clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_number', name='uq_sales_delivery_number')
    )
    op.create_index(op.f('ix_sales_delivery_notes_client_id'), 'sales_delivery_notes', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_delivery_notes_delivery_date'), 'sales_delivery_notes', ['delivery_date'], unique=False)
    op.create_index(op.f('ix_sales_delivery_notes_delivery_number'), 'sales_delivery_notes', ['delivery_number'], unique=False)
    op.create_index(op.f('ix_sales_delivery_notes_sales_order_id'), 'sales_delivery_notes', ['sales_order_id'], unique=False)
    op.create_table('sales_delivery_items',
    sa.Column('delivery_note_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_item_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_delivery_item_qty_positive'),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['sales_delivery_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_item_id'], ['sales_order_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_delivery_items_delivery_note_id'), 'sales_delivery_items', ['delivery_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_delivery_items_delivery_note_id'), table_name='sales_delivery_items')
    op.drop_table('sales_delivery_items')
    op.drop_index(op.f('ix_sales_delivery_notes_sales_order_id'), table_name='sales_delivery_notes')
    op.drop_index(op.f('ix_sales_delivery_notes_delivery_number'), table_name='sales_delivery_notes')
    op.drop_index(op.f('ix_sales_delivery_notes_delivery_date'), table_name='sales_delivery_notes')
    op.drop_index(op.f('ix_sales_delivery_notes_client_id'), table_name='sales_delivery_notes')
    op.drop_table('sales_delivery_notes')
    # ### end Alembic commands ###
