"""payment request model updated

Revision ID: 1d2b9df8e236
Revises: ea3f3ea0ac3f
Create Date: 2026-08-02 08:39:28.304780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d2b9df8e236'
down_revision: Union[str, Sequence[str], None] = 'ea3f3ea0ac3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_requests', sa.Column('request_number', sa.String(length=30), nullable=False))
    op.add_column('payment_requests', sa.Column('odoo_reference', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_payment_requests_request_number'), 'payment_requests', ['request_number'], unique=True)
    op.create_unique_constraint('uq_payment_requests_number', 'payment_requests', ['request_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_payment_requests_number', 'payment_requests', type_='unique')
    op.drop_index(op.f('ix_payment_requests_request_number'), table_name='payment_requests')
    op.drop_column('payment_requests', 'odoo_reference')
    op.drop_column('payment_requests', 'request_number')
    # ### end Alembic commands ###
