"""add supply_consumption model

Revision ID: 27cde667baae
Revises: 3071cb61f459
Create Date: 2026-08-15 18:17:02.962055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27cde667baae'
down_revision: Union[str, Sequence[str], None] = '3071cb61f459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_line_consumptions',
    sa.Column('supply_request_item_id', sa.UUID(), nullable=False),
    sa.Column('purchase_request_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_slc_quantity_positive'),
    sa.ForeignKeyConstraint(['purchase_request_item_id'], ['purchase_request_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supply_request_item_id'], ['supply_request_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supply_request_item_id', 'purchase_request_item_id', name='uq_slc_supply_purchase')
    )
    op.create_index(op.f('ix_supply_line_consumptions_purchase_request_item_id'), 'supply_line_consumptions', ['purchase_request_item_id'], unique=False)
    op.create_index(op.f('ix_supply_line_consumptions_supply_request_item_id'), 'supply_line_consumptions', ['supply_request_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_line_consumptions_supply_request_item_id'), table_name='supply_line_consumptions')
    op.drop_index(op.f('ix_supply_line_consumptions_purchase_request_item_id'), table_name='supply_line_consumptions')
    op.drop_table('supply_line_consumptions')
    # ### end Alembic commands ###
