"""add sales_proforma model

Revision ID: 2dc2d3617900
Revises: b519dab930d1
Create Date: 2026-08-17 22:34:55.203318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc2d3617900'
down_revision: Union[str, Sequence[str], None] = 'b519dab930d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_proformas',
    sa.Column('proforma_number', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('proforma_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('converted_sale_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('en_cours','convertie')", name='ck_sales_proforma_status'),
    sa.ForeignKeyConstraint(['client_id'], ['sales_clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['converted_sale_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proforma_number', name='uq_sales_proformas_number')
    )
    op.create_index(op.f('ix_sales_proformas_client_id'), 'sales_proformas', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_proformas_proforma_date'), 'sales_proformas', ['proforma_date'], unique=False)
    op.create_index(op.f('ix_sales_proformas_proforma_number'), 'sales_proformas', ['proforma_number'], unique=False)
    op.create_table('sales_proforma_items',
    sa.Column('proforma_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sales_proforma_item_qty_positive'),
    sa.CheckConstraint('sale_price >= 0', name='ck_sales_proforma_item_price_nonneg'),
    sa.ForeignKeyConstraint(['product_id'], ['sales_products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proforma_id'], ['sales_proformas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_proforma_items_proforma_id'), 'sales_proforma_items', ['proforma_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_proforma_items_proforma_id'), table_name='sales_proforma_items')
    op.drop_table('sales_proforma_items')
    op.drop_index(op.f('ix_sales_proformas_proforma_number'), table_name='sales_proformas')
    op.drop_index(op.f('ix_sales_proformas_proforma_date'), table_name='sales_proformas')
    op.drop_index(op.f('ix_sales_proformas_client_id'), table_name='sales_proformas')
    op.drop_table('sales_proformas')
    # ### end Alembic commands ###
