"""add center_request model

Revision ID: 43d9ffe110e2
Revises: 2dc2d3617900
Create Date: 2026-08-18 09:22:36.536715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d9ffe110e2'
down_revision: Union[str, Sequence[str], None] = '2dc2d3617900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('center_requests',
    sa.Column('request_number', sa.String(length=30), nullable=False),
    sa.Column('vehicle_brand', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('plate_number', sa.String(length=30), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('nouvelle','preparee','envoyee')", name='ck_center_requests_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number', name='uq_center_requests_number')
    )
    op.create_index(op.f('ix_center_requests_created_by'), 'center_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_center_requests_request_date'), 'center_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_center_requests_request_number'), 'center_requests', ['request_number'], unique=False)
    op.create_index(op.f('ix_center_requests_status'), 'center_requests', ['status'], unique=False)
    op.create_table('center_request_items',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('prepared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_center_item_qty_positive'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['center_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_request_items_request_id'), 'center_request_items', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_center_request_items_request_id'), table_name='center_request_items')
    op.drop_table('center_request_items')
    op.drop_index(op.f('ix_center_requests_status'), table_name='center_requests')
    op.drop_index(op.f('ix_center_requests_request_number'), table_name='center_requests')
    op.drop_index(op.f('ix_center_requests_request_date'), table_name='center_requests')
    op.drop_index(op.f('ix_center_requests_created_by'), table_name='center_requests')
    op.drop_table('center_requests')
    # ### end Alembic commands ###
