"""add purchase request model

Revision ID: 9a393932d6d2
Revises: c22b53b4bfa2
Create Date: 2026-08-02 16:39:39.143596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a393932d6d2'
down_revision: Union[str, Sequence[str], None] = 'c22b53b4bfa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requests',
    sa.Column('bc_number', sa.String(length=30), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','sent','received')", name='ck_purchase_requests_status'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bc_number', name='uq_purchase_requests_number')
    )
    op.create_index(op.f('ix_purchase_requests_bc_number'), 'purchase_requests', ['bc_number'], unique=True)
    op.create_index(op.f('ix_purchase_requests_request_date'), 'purchase_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_purchase_requests_status'), 'purchase_requests', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_requests_supplier_id'), 'purchase_requests', ['supplier_id'], unique=False)
    op.create_table('purchase_request_items',
    sa.Column('purchase_request_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_pr_item_quantity_positive'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_request_id', 'part_id', name='uq_pr_item_request_part')
    )
    op.create_index(op.f('ix_purchase_request_items_part_id'), 'purchase_request_items', ['part_id'], unique=False)
    op.create_index(op.f('ix_purchase_request_items_purchase_request_id'), 'purchase_request_items', ['purchase_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_request_items_purchase_request_id'), table_name='purchase_request_items')
    op.drop_index(op.f('ix_purchase_request_items_part_id'), table_name='purchase_request_items')
    op.drop_table('purchase_request_items')
    op.drop_index(op.f('ix_purchase_requests_supplier_id'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_status'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_request_date'), table_name='purchase_requests')
    op.drop_index(op.f('ix_purchase_requests_bc_number'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    # ### end Alembic commands ###
