"""add sale payment model

Revision ID: b519dab930d1
Revises: 0495e061bf6a
Create Date: 2026-08-17 21:21:35.652208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b519dab930d1'
down_revision: Union[str, Sequence[str], None] = '0495e061bf6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_payments',
    sa.Column('payment_number', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_sales_payment_amount_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['sales_clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number', name='uq_sales_payments_number')
    )
    op.create_index(op.f('ix_sales_payments_client_id'), 'sales_payments', ['client_id'], unique=False)
    op.create_index(op.f('ix_sales_payments_payment_date'), 'sales_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_sales_payments_payment_number'), 'sales_payments', ['payment_number'], unique=False)
    op.create_table('sales_payment_allocations',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_sales_alloc_amount_positive'),
    sa.ForeignKeyConstraint(['payment_id'], ['sales_payments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'sales_order_id', name='uq_sales_alloc_payment_order')
    )
    op.create_index(op.f('ix_sales_payment_allocations_payment_id'), 'sales_payment_allocations', ['payment_id'], unique=False)
    op.create_index(op.f('ix_sales_payment_allocations_sales_order_id'), 'sales_payment_allocations', ['sales_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_payment_allocations_sales_order_id'), table_name='sales_payment_allocations')
    op.drop_index(op.f('ix_sales_payment_allocations_payment_id'), table_name='sales_payment_allocations')
    op.drop_table('sales_payment_allocations')
    op.drop_index(op.f('ix_sales_payments_payment_number'), table_name='sales_payments')
    op.drop_index(op.f('ix_sales_payments_payment_date'), table_name='sales_payments')
    op.drop_index(op.f('ix_sales_payments_client_id'), table_name='sales_payments')
    op.drop_table('sales_payments')
    # ### end Alembic commands ###
