"""add centre role to users constraint

Revision ID: b850bc69c669
Revises: dfcb7853d654
Create Date: 2026-08-18 10:53:05.496171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b850bc69c669'
down_revision: Union[str, Sequence[str], None] = 'dfcb7853d654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # Supprimer l'ancienne contrainte
    op.drop_constraint('ck_users_role', 'users', type_='check')
    # Créer la nouvelle
    op.create_check_constraint(
        'ck_users_role',
        'users',
        "role IN ('admin', 'magazinier', 'centre')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
