"""add inventory model

Revision ID: c22b53b4bfa2
Revises: 1d2b9df8e236
Create Date: 2026-08-02 13:42:56.145674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22b53b4bfa2'
down_revision: Union[str, Sequence[str], None] = '1d2b9df8e236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_counts',
    sa.Column('count_number', sa.String(length=30), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('count_number', name='uq_inventory_counts_number')
    )
    op.create_index(op.f('ix_inventory_counts_count_date'), 'inventory_counts', ['count_date'], unique=False)
    op.create_index(op.f('ix_inventory_counts_count_number'), 'inventory_counts', ['count_number'], unique=True)
    op.create_table('inventory_count_items',
    sa.Column('inventory_count_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('counted_quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('counted_quantity >= 0', name='ck_count_item_qty_nonneg'),
    sa.ForeignKeyConstraint(['inventory_count_id'], ['inventory_counts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_count_id', 'part_id', name='uq_count_item_count_part')
    )
    op.create_index(op.f('ix_inventory_count_items_inventory_count_id'), 'inventory_count_items', ['inventory_count_id'], unique=False)
    op.create_index(op.f('ix_inventory_count_items_part_id'), 'inventory_count_items', ['part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_count_items_part_id'), table_name='inventory_count_items')
    op.drop_index(op.f('ix_inventory_count_items_inventory_count_id'), table_name='inventory_count_items')
    op.drop_table('inventory_count_items')
    op.drop_index(op.f('ix_inventory_counts_count_number'), table_name='inventory_counts')
    op.drop_index(op.f('ix_inventory_counts_count_date'), table_name='inventory_counts')
    op.drop_table('inventory_counts')
    # ### end Alembic commands ###
