"""add supply request

Revision ID: e5a6e1945575
Revises: aec8c796efce
Create Date: 2026-08-04 15:15:47.976127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5a6e1945575'
down_revision: Union[str, Sequence[str], None] = 'aec8c796efce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_requests',
    sa.Column('sr_number', sa.String(length=30), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open','in_progress','fulfilled')", name='ck_supply_requests_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sr_number', name='uq_supply_requests_number')
    )
    op.create_index(op.f('ix_supply_requests_created_by'), 'supply_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_supply_requests_request_date'), 'supply_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_supply_requests_sr_number'), 'supply_requests', ['sr_number'], unique=True)
    op.create_index(op.f('ix_supply_requests_status'), 'supply_requests', ['status'], unique=False)
    op.create_table('supply_request_items',
    sa.Column('supply_request_id', sa.UUID(), nullable=False),
    sa.Column('part_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_sr_item_quantity_positive'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supply_request_id'], ['supply_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supply_request_id', 'part_id', name='uq_sr_item_request_part')
    )
    op.create_index(op.f('ix_supply_request_items_part_id'), 'supply_request_items', ['part_id'], unique=False)
    op.create_index(op.f('ix_supply_request_items_supply_request_id'), 'supply_request_items', ['supply_request_id'], unique=False)
    op.add_column('purchase_requests', sa.Column('supply_request_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'purchase_requests', 'supply_requests', ['supply_request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_requests', type_='foreignkey')
    op.drop_column('purchase_requests', 'supply_request_id')
    op.drop_index(op.f('ix_supply_request_items_supply_request_id'), table_name='supply_request_items')
    op.drop_index(op.f('ix_supply_request_items_part_id'), table_name='supply_request_items')
    op.drop_table('supply_request_items')
    op.drop_index(op.f('ix_supply_requests_status'), table_name='supply_requests')
    op.drop_index(op.f('ix_supply_requests_sr_number'), table_name='supply_requests')
    op.drop_index(op.f('ix_supply_requests_request_date'), table_name='supply_requests')
    op.drop_index(op.f('ix_supply_requests_created_by'), table_name='supply_requests')
    op.drop_table('supply_requests')
    # ### end Alembic commands ###
