"""add tariff modul

Revision ID: f8685b9dbadd
Revises: 0ee2e484bc63
Create Date: 2026-09-22 11:48:41.930659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8685b9dbadd'
down_revision: Union[str, Sequence[str], None] = '0ee2e484bc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_articles',
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_articles_designation'), 'tariff_articles', ['designation'], unique=False)
    op.create_table('tariff_suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_tariff_suppliers_name')
    )
    op.create_index(op.f('ix_tariff_suppliers_name'), 'tariff_suppliers', ['name'], unique=False)
    op.create_table('tariff_prices',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_tariff_price_nonneg'),
    sa.ForeignKeyConstraint(['article_id'], ['tariff_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['tariff_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_prices_article_id'), 'tariff_prices', ['article_id'], unique=False)
    op.create_index(op.f('ix_tariff_prices_supplier_id'), 'tariff_prices', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariff_prices_supplier_id'), table_name='tariff_prices')
    op.drop_index(op.f('ix_tariff_prices_article_id'), table_name='tariff_prices')
    op.drop_table('tariff_prices')
    op.drop_index(op.f('ix_tariff_suppliers_name'), table_name='tariff_suppliers')
    op.drop_table('tariff_suppliers')
    op.drop_index(op.f('ix_tariff_articles_designation'), table_name='tariff_articles')
    op.drop_table('tariff_articles')
    # ### end Alembic commands ###
